ga:
  population_size: 1000
  crossover_probability: 0.5
  mutation_probability: 0.5
  generations: 10

cma_es:
  population_size: 100
  generations: 10
  sigma: 0.5
  learning_rate: 0.1

cppn:
  population_size: 5
  crossover_probability: 0.5
  mutation_probability: 0.5
  generations: 5

pso:
  population_size: 10
  generations: 10
  inertia: 0.5
  cognitive_coefficient: 0.5
  social_coefficient: 0.5
