ga:
  population_size: 100
  crossover_probability: 0.2
  mutation_probability: 0.9
  generations: 300
  max_mutpb: 0.9
  min_mutpb: 0.5
  mutpb_delta: 0.01
  max_cxpb: 0.9
  min_cxpb: 0.1
  cxpb_delta: 0.01
  stagnation: 5


cma_es:
  population_size: 1000
  generations: 100
  sigma: 0.5
  learning_rate: 0.1

cppn:
  population_size: 500
  crossover_probability: 0.5
  mutation_probability: 0.5
  generations: 50
  dim_z: 32
  dim_x: 224
  dim_y: 224
  ch: 32
  scale: 10.0

pso:
  population_size: 40
  generations: 10
  inertia: 0.5
  cognitive_coefficient: 0.5
  social_coefficient: 0.5
