dataset: cifar10
network: resnet18
weights_path: '/home/disi/project2/weights/resnet18_best_model.pth'

ga:
  population_size: 300
  crossover_probability: 0.5
  mutation_probability: 0.5
  generations: 200

cma_es:
  population_size: 300
  generations: 200
  sigma: 0.1
  learning_rate: 0.1

cppn:
  population_size: 10
  crossover_probability: 0.5
  mutation_probability: 0.5
  generations: 10

pso:
  population_size: 300
  generations: 50
  inertia: 0.5
  cognitive_coefficient: 0.5
  social_coefficient: 0.5
